title: Muhammad Alfisyahrin Muzhaffar
email: alfisyahrinmuzhaffar@gmail.com
description: > 
    Halo! Saya adalah Mahasiswa Teknik Informatika 
    di Politeknik Negeri Lhokseumawe, lahir di kota penuh cerita, Lhokseumawe, 20 Oktober 2006.Di blog ini, saya nulis seputar dunia teknologi, coding, dan perjalanan belajar saya. 
    Gak cuma berbagi ilmu, tapi juga pengalaman yang (semoga) bisa jadi manfaat buat kamu semua. 
    Stay tune, karena di sini tempatnya belajar sambil santai!

url: "https://alfisyahrin-26.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag